# mapping of country names
mapping = {
    'Cape Verde': 'Cabo Verde',
    'Czech Republic': 'Czechia',
    'Côte d\'Ivoire': 'Ivory Coast',
    'Republic of the Congo': 'Congo Republic',
    'Congo, Democratic Republic of the': 'DR Congo',
    'Curacao': 'Curaçao',
    'United Republic of Tanzania': 'Tanzania',
    'Hong Kong, China': 'Hong Kong',
    'Korea, Democratic People\'s Republic of': 'North Korea',
    'Korea, Republic of': 'South Korea',
    'Macao, China': 'Macao',
    'Taiwan Province of China': 'Taiwan',
    'Brunei Darussalam': 'Brunei',
    'Lao People\'s Democratic Republic': 'Laos',
    'Myanmar [Burma]': 'Myanmar',
    'East Timor': 'Timor-Leste',
    'Viet Nam': 'Vietnam',
    'Iran, Islamic Republic of': 'Iran',
    'State of Palestine': 'Palestine',
    'Syrian Arab Republic': 'Syria',
    'Bolivia, Plurinational State of': 'Bolivia',
    'Venezuela, Bolivarian Republic of': 'Venezuela',
    'Curacao': 'Curaçao',
    'Micronesia, Federated States of': 'Micronesia',
    'The former Yugoslav Republic of Macedonia': 'Macedonia',
    'Moldova, Republic of': 'Moldova',
    'Reunion': 'Réunion',
    'Russian Federation': 'Russia',
    'Saint Kitts and Nevis': 'St Kitts and Nevis',
    'Saint Vincent and the Grenadines': 'St Vincent and Grenadines',
    'Swaziland': 'Eswatini',
    'Sao Tome and Principe': 'São Tomé and Príncipe'
}
df_un['Region/economy'] = df_un['Region/economy'].apply(lambda x: mapping.get(x, x))
